### ISSUE TITLE
Getting ffmpeg binary can lead to IOError

### ISSUE THREAD

**Issue by smathot** [expyriment/expyriment#122]
When Expyriment is imported, `Video.get_ffmpeg_binary()` is called. There are two problems with this.

The first is conceptual: I don't think it's well behaved to download something automatically when a library is imported. Wouldn't it be better to do this the first time that a `Video` object is instantiated?

The second is technical: Within `get_ffmpeg_binary()`, you catch `ImportError`s and `imageio.core.NeedDownloadError`s. However, you can also get an `IOError` if `imageio.plugins.ffmpeg.download()` fails. I think this happens when there seems to be an internet connection, but the download for some reason doesn't succeed. This was the case yesterday on several university computers. And because of the way that `get_ffmpeg_binary()` is always called, this completely breaks Expyriment!

My suggestion would be to solve both, by only downloading when this makes sense, and then catching also `IOError`s during the download.

This was on Expyriment 0.9.1b2 on Windows 10, Python 2.7. (I.e. the OpenSesame 3.2.0a22 prerelease)

**Comment by fladd** [comment]
@lindemann09 What do you think? Shall we change the default behaviour to only download ffmpeg when the first video is trying to be played?

I think our rationale before was to make it easy to do a full Expyriment installation on a lab computer. Since probably everyone checks if the import of Expyriment works after installation, we decided to at this point also check if ffmpeg is available and if not, try to download it.

If we change it to only check and download once video playback is actually used, people (me at least) will probably constantly forget to also set up video playback on lab computers (where internet might not be available at all times for instance), leading to "incomplete" installations.

**Comment by fladd** [comment]
Ideally ffmpeg would be installed while getting Expyriment from pip. Unfortunately, this is not possible.

**Comment by smathot** [comment]
Thanks! That looks good to me.
