### ISSUE TITLE
Font 'None' not found error on Mac OS

### ISSUE THREAD

**Issue by smathot** [expyriment/expyriment#123]
Hi guys (cc @dschreij),

When initializing Expyriment 0.9.1b2 on a clean Mac, within OpenSesame, the following error occurs (on some systems). The cause of the error is not entirely clear to me, but I suspect Expyriment looks for a font outside of the Python environment (in this case the Anaconda environment of OpenSesame) and cannot find it.

~~~ python
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/libqtopensesame/misc/process.py", line 154, in run
    exp.run()
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/libopensesame/experiment.py", line 396, in run
    self.init_display()
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/libopensesame/experiment.py", line 661, in init_display
    canvas.init_display(self)
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/openexp/canvas.py", line 67, in init_display
    cls.init_display(experiment)
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/openexp/_canvas/xpyriment.py", line 97, in init_display
    exp = control.initialize()
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/expyriment/control/_experiment_control.py", line 454, in initialize
    position=(0, -5))
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/expyriment/stimuli/_textline.py", line 102, in __init__
    raise IOError("Font '{0}' not found!".format(text_font))
IOError: Font 'None' not found!
~~~

Cheers,
Sebastiaan

**Comment by smathot** [comment]
I just tested this on the Mac that suffers from this issue, and it's actually not fixed (although my pull request does fix some odd logic). The problem seems to lie deeper, in that `pygame.font.get_fonts()` returns `[None]` on that system.

**Comment by fladd** [comment]
The logic of finding fonts was actually to always fall back to the default. The default is "FreeSans". Expyriment will then try to find this with `pygame.font.match_font("FreeSans")` in `misc.find_font`. If this is not successful, this will return an empty string. It is hence not clear to me, how you can possibly end up with a `None` there (it should be an empty string if anything, but that also should never happen, because FreeSans is delivered with Expyriment and should hence always be available; we do add this font in `misc.__init__`. It hence can never be that the internal font is not found. Your fix should not be necessary. I am confused.

This makes me believe that you are trying to use a different font then the Expyriment default. Is this correct? Because, you are apparently not running into the else clause in line 96 (since this would lead to an empty string and not None). It would be good the exact trace of events in the `init` of `TextLine` on this machine. There seems to be a different error with external fonts.

**Comment by smathot** [comment]
The reason that it seems to end up with `None` is that the error message was incorrect. I fixed this, and then you indeed see that it complains about a `''` (empty string) font as returned by `find_font()`.

As far as I can tell, the root of the issue is that the PyGame font module is broken, but for some reason specifically on this Mac OS system. On other systems it works ok.

So my patch doesn't fix this issue. It's still a sensible patch though, avoiding other potential issues.

**Comment by fladd** [comment]
Ah, I see. Yes, that makes sense. I am also puzzled about why the font system is broken on that particular system...I tried to understand font caching on OS X once but gave up. On my system I have the opposite issue: It rescans the fonts very often, even though I did not change anything. The same goes for Gimp (which also often scans for fonts on startup very long). What happens when you actually install a new system font? Will it update the cache then?

**Comment by smathot** [comment]
> What happens when you actually install a new system font? Will it update the cache then?

I don't know. It's the laptop of a student, so I cannot really do much testing on it. For now, I think we can assume that this is a relatively rare issue. Don't you?

**Comment by fladd** [comment]
Probably. Still bugs me, though :-)

**Comment by fladd** [comment]
Mmh, just looked at it again, and `pygame.font.match_font(pygame.font.get_fonts()[0])` will not work correctly, since this list is not ordered. For me it returns `'/System/Library/Fonts/Apple Color Emoji.ttc'`. Not what one wants :-)
I think my initial code was almost correct. I made some minor changes now that it always should work (on a system that is not broken; I "hardcoded" `"FreeSans"` as last resort, which is the font we ship with Expyriment) and the exception will always tell the name the user knows of the font (it hence will not say `None` or `""` anymore; I reverted your change, since this will mention the filename, which is not so informative, if it cannot be found).
I hope this works now consistently.

**Comment by smathot** [comment]
Ok great. We're going to release OpenSesame 3.2.0 very soon, as in the next coming days. Any chance that you'll tag Expryiment 0.9.1 as stable by then? If not, we'll ship a prerelease (which has been working fine except for the minor issues that you know of), and then update with OpenSesame 3.2.1.

**Comment by fladd** [comment]
I am afraid not. There are still several bugs in the beta (most are regressions due to the change to Python 3) that we would like to fix for a final release. And given the amount of bugs, we will need another round of beta testing.

**Comment by dschreij** [comment]
Hmm @smathot, do you think the bugs @fladd is talking about could also affect OpenSesame in the way it uses expyriment?
@fladd, what are the most pressing, deal-breaking bugs you'd like to have fixed before a next release?

**Comment by smathot** [comment]
OpenSesame uses only a subset of the functionality of Expyriment, and after pretty long use I haven't noticed any bugs. But I agree it would be good to have an overview of outstanding issues.

**Comment by memming** [comment]
I having a similar issue where `expyriment` can't find fonts on Mac OS X (anaconda). Default font name seems to be an empty string.

> pygame 1.9.6
> Hello from the pygame community. https://www.pygame.org/contribute.html
> Expyriment 0.9.0 (Python 3.7.3)
> psychopyshics.py
> Initializing system fonts. This might take a couple of minutes...
> Traceback (most recent call last):
>   File "/anaconda3/envs/blah/lib/python3.7/site-packages/expyriment/stimuli/_textline.py", line 99, in __init__
>     with open(self._text_font, 'rb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: ''
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "psychopyshics.py", line 4, in <module>
>     expyriment.control.initialize(exp)
>   File "/anaconda3/envs/blah/lib/python3.7/site-packages/expyriment/control/_experiment_control.py", line 454, in initialize
>     position=(0, -5))
>   File "/anaconda3/envs/blah/lib/python3.7/site-packages/expyriment/stimuli/_textline.py", line 102, in __init__
>     raise IOError("Font '{0}' not found!".format(text_font))
> OSError: Font 'None' not found!
