### ISSUE TITLE
Visual stimulus test suite crashes before reporting

### ISSUE THREAD

**Issue by wjhopper** [expyriment/expyriment#131]
When I run the visual stimulus test suite (9.1b2 pre-release version) from the Windows 7 `cmd` terminal using the `experiment.cli` module, or from the vanilla Python shell, it crashes with the following error before the reporting screen:

`C:\Users\will>python -m expyriment.cli -T`
```python
Traceback (most recent call last):
File "C:\Users\will\Anaconda3\envs\xpy_9_1_beta\lib\runpy.py", line 193, in _run_module_as_main
  "__main__", mod_spec)
File "C:\Users\will\Anaconda3\envs\xpy_9_1_beta\lib\runpy.py", line 85, in _run_code
  exec(code, run_globals)
File "C:\Users\will\Anaconda3\envs\xpy_9_1_beta\lib\site-packages\expyriment\cli.py", line 294, in <module>
  main()
File "C:\Users\will\Anaconda3\envs\xpy_9_1_beta\lib\site-packages\expyriment\cli.py", line 217, in main
  control.run_test_suite()
File "C:\Users\will\Anaconda3\envs\xpy_9_1_beta\lib\site-packages\expyriment\control\_test_suite.py", line 597, in run_test_suite
  rtn = _stimulus_timing(exp)
File "C:\Users\will\Anaconda3\envs\xpy_9_1_beta\lib\site-packages\expyriment\control\_test_suite.py", line 354, in _stimulus_timing
  return _test1()
File "C:\Users\will\Anaconda3\envs\xpy_9_1_beta\lib\site-packages\expyriment\control\_test_suite.py", line 194, in _test1
  inaccuracies.extend([key % (1000 // refresh_rate)] * hist[key])
ZeroDivisionError: float modulo
```

During the visual stimulus test, there is obvious flickering/tearing of the left rectangle. Strangely, when I run the test suite from an IPython console (using `expyriment.control.run_test_suite()`), there is no flickering/tearing, and the report finishes just fine!

My system information is as follows:
```python
expyriment.misc.get_system_info()
{'hardware_audio_card': '',
 'hardware_cpu_architecture': 'AMD64',
 'hardware_cpu_details': 'Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz',
 'hardware_cpu_type': 'Intel64 Family 6 Model 69 Stepping 1, GenuineIntel',
 'hardware_disk_space_free': '26838 MB',
 'hardware_disk_space_total': '152587 MB',
 'hardware_internet_connection': 'Yes',
 'hardware_memory_free': '1921 MB',
 'hardware_memory_total': '8097 MB',
 'hardware_ports_parallel': [],
 'hardware_ports_parallel_driver': None,
 'hardware_ports_serial': [],
 'hardware_video_card': 'RDPDD Chained DD',
 'os_architecture': '64bit',
 'os_details': 'SP1',
 'os_name': 'Windows',
 'os_platform': 'Windows',
 'os_release': '7',
 'os_version': '6.1.7601',
 'python_expyriment_build_date': 'Sun Dec 24 18:55:40 2017 +0100',
 'python_expyriment_revision': 'd99f4b0',
 'python_expyriment_version': '0.9.1b2',
 'python_mediadecoder_version': '0.1.5',
 'python_numpy_version': '1.14.2',
 'python_pil_version': '1.1.7',
 'python_pygame_version': '1.9.3',
 'python_pyopengl_version': '3.1.0',
 'python_pyparallel_version': '',
 'python_pyserial_version': '3.4',
 'python_sounddevice_version': '0.3.10',
 'python_version': '3.6.4',
 'settings_folder': None}
```

**Comment by fladd** [comment]
Hi there,

the output of your system info suggests that you were running through remote desktop. Is this correct?

**Comment by wjhopper** [comment]
Definitely not! I was wondering what "RDPDD Chained DD" was about. This laptop has a Intel integrated graphics card, model 4400. I

**Comment by fladd** [comment]
That is very strange. According to [Wikipedia](https://en.wikipedia.org/wiki/Mirror_driver), this driver is used for remote displays.

It appears that the `refresh_rate` that is calculated is higher than `1000` for some reason. We should catch this situation in the future.

For now, I suggest to test again with the alternative blocking method (since blocking clearly does not work with the default method - something we experience on a lot of Intel integrated graphics).

**Note to myself**
A possible solution might be:
```
[key % max(1, (1000 // refresh_rate))] * hist[key]
```

**Comment by wjhopper** [comment]
The mis-detection of the graphics card refresh rate persists using `expyriment.control.defaults.open_gl = 1`, `expyriment.control.defaults.open_gl = 2` and `expyriment.control.defaults.open_gl = 3`, and the test suite still has flickering/tearing and crashes with the same `ZeroDivisionError` error.

When I run the test suite from the IPython console, the visual stimulus test suite runs to completetion, and reports a refresh rate anywhere between about 750 and 890 Hz, which does appear to be erroneous.

I could try updating the drivers, if you think that would be helpful (the driver I have installed was released in 2015).

**Comment by fladd** [comment]
Mmh, the fact that it runs in iPython is most strange. Is this using the same Python distribution?

Just to rule out that the issue is related to Anaconda: Does the same mis-detection occur when using the official Python distribution (www.python.org)?

You might also want to check the settings of your graphics card. Usually, you want to switch off any power saving modes and set the graphics card to sync to the vertical retrace (if this option is offered in the settings). That, together with `open_gl=3` will work most of the time. However, there of course might be graphics cards with suboptimal Windows drivers, that do not allow for a proper blocking on the vertical retrace.

The `ZeroDivisionError` we will fix in a future update, so you can at least use your machine to develop your experiment on (as for this the timing might not be that important). I would, however, suggest to not test actual participants on a machine that does not properly block on the vertical retrace.

**Comment by wjhopper** [comment]
With latest drivers from intel's website, the "maximum performance" power setting, and forcing the card to sync to the vertical retrace (they don't make that setting easy to find!), the visual stimulus test suite runs to completion:

- From the command line using `python -m expyriment.cli -T`
- From the vanilla Python shell using `expyriment.control.run_test_suite()`
- From the IPython shell using `expyriment.control.run_test_suite()`

Now, the test shows tearing/flickering on *both* rectangles when run from the cli or vanilla Python shell instead of just the left one, but still a stable image when run from the IPython shell. It is using the same Python distribution in both cases (3.6.4, from Anaconda). The results are the same with `open_gl=3` and `open_gl=2`. I'll install the official Python distribution, and edit this post to reflect the results.

The good news is, the monitor's refresh rate (60 Hz) is accurately detected after changing those driver settings. 

The bad news is, the timing performance is still terrible =) haha the average delay is always 7ms, and the percent of unexplained timing delays is between 80% and 90% on each run. So, yes, participants should not be run on this machine. It would probably work better if it wasn't trying to use a remote desktop driver for some reason!

Thanks for all your help, I guess this bug report was a symptom of bigger problems on this machine. I can appreciate that it's not easy to write code that deals with an effectively impossible system.
