### ISSUE TITLE
Crash with rotate

### ISSUE THREAD

**Issue by Wittgensteindu30** [expyriment/expyriment#211]
Hi,

I am getting the following error while trying to rotate a canvas: 

```
    Fatal Python error: PyEval_SaveThread: NULL tstate

     Current thread 0x00000804 (most recent call first):
      File "C:\Users\33652\anaconda3\envs\expyriment\lib\site-packages\expyriment\stimuli\_visual.py", line 1295 in rotate
     File "canvas_rotation.py", line 38 in <module> (expyriment)
```

I found a workaround (in the pygame/pygame github repository's issues) using `pygame.transform.rotozoom`:

```
    surf_stim = canvas_stim.get_surface_copy()
    surf_stim = rotozoom(surf_stim, i*rotation_angle, 1.0)
    new_canvas = stimuli.Canvas(size=(300,300),colour= black)
    new_canvas.set_surface(surf_stim)
```

**Comment by fladd** [comment]
Hi @Wittgensteindu30,

Expyriment already uses rotozoom by default for rotating stimuli. It is only when you call a stimulus' rotate method explicitly with the argument `filter=False` that it uses the non-rotating zoom. Looking at your error message, it seems that this is what you did (since the error happens in line 1295, which is only called when filter is False). So the quickest solution in your case would be to just call the rotate method without a second argument.

However, I also cannot replicate the error when explicitly using `filter=False`, like in your case. (Windows 10, Python 3.8, Expyriment 0.10.0). I see that you are using Anaconda. Could you maybe try whether you also get the error with the official Python (from python.org)?
