### ISSUE TITLE
cannot import expyriment on osx with python 3.5

### ISSUE THREAD

**Issue by dschreij** [expyriment/expyriment#99]
Hi guys,

I just dit an update of the python3 branch, and now I get this message when I try to import expyriment:

~~~
(opensesame-qt5-py3) [daniel @ ~]: python
Python 3.5.3 | packaged by conda-forge | (default, Jan 24 2017, 06:45:37) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import expyriment
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daniel/anaconda/envs/opensesame-qt5-py3/lib/python3.5/site-packages/expyriment/__init__.py", line 49, in <module>
    raise ImportError(m)
ImportError: Expyriment cannot be imported where a file 'test.py' exists!
Please remove or rename test.py and try again.' 
~~~
There is no file `test.py` as far as I can see. Do you have any idea what may cause this problem?

**Comment by dschreij** [comment]
By the way, I had to install a module called `test` with pip (which seems a really strange name to use for a serious module on pip to me), otherwise I get:

~~~
(opensesame-qt5-py3) [daniel @ ~]: python
Python 3.5.3 | packaged by conda-forge | (default, Jan 24 2017, 06:45:37) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import expyriment
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daniel/anaconda/envs/opensesame-qt5-py3/lib/python3.5/site-packages/expyriment/__init__.py", line 40, in <module>
    import test as _test
ImportError: No module named 'test'
~~~

Is that correct?

**Comment by fladd** [comment]
Hi Daniel,

the package `future`, which is a dependency of Expyriment, does import the package `test`. This is part of the Python standard library (https://docs.python.org/3/library/test.html), so you do not have to install any `test` package from pip.

The reason you see this error is that I realized that I very often write a `test.py` script to, well, quickly test things. The problem with this is that this will shadow the `test` package from the standard library, which `future` tries to import. The effect of this is that my `test.py` script (whatever the contents are) will be imported (and hence executed) every time Expyriment is imported.

Since I thought that writing a testing script is common among Expyriment users, and that `test.py` will be a common choice for the name of such a script, I wanted to somehow prevent people from running into this issue of shadowing the actual `test` package by accident. I am aware that people can in theory shadow all kinds of things (e.g. they could create a `sys.py` or an `os.py`), but I thought naming a script `test.py` is common enough to be treated as a special case.

That is why in the newest version, Expyriment will as the first thing check whether the to be imported `test` is a file, which would be indicative of a user script shadowing the `test` package from the standard library.
If you pull again, you will see that I now also print the full path of the user script that causes the shadowing, such that you can rename or remove it.
We could also think about printing a warning only instead of throwing an exception.

I hope this explanation clarifies the issue.

P.S.: I am totally puzzled that you had to install something from pip, as `test` is part of the standard library. I now wrapped the code in a `try`-`catch` just to be sure, though.

**Comment by fladd** [comment]
Should be fixed in https://github.com/expyriment/expyriment/releases/tag/v0.9.0rc4

**Comment by dschreij** [comment]
Hi Florian,

it seems to be fixed! I no longer get the error.

**Comment by fladd** [comment]
Hi Daniel,

good to hear.

In case you have a local `test.py{c|o|d}`, there will now only be a warning printed in the console when importing Expyriment.
